"""
Django settings for Core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os
from decouple import config, Csv

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

SENTRY_DSN = config('SENTRY_DSN', default='')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=1.0, # Adjust to a lower value in high-traffic production
        send_default_pii=True,
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-&@j7sauie)^w-$0#jjr%j6e$k^3@2#!*!mbs1_10ykbva+bewt'
SECRET_KEY = config('SECRET_KEY', default='django-insecure-pms-local-dev-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1,127.0.0.1:8000', cast=Csv())



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'drf_yasg',
    # Local apps
    'Auth',
    'Reception',
    'Farms',
    'Health',
    'HumanResources',
    'Stores',
    'Messaging',
    'Cases',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS middleware (should be early)
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # ==================================================
    # PHASE 1 MIDDLEWARE (Organizational hierarchy)
    # ==================================================
    # Order matters! OrgContext must run before AccessScope and AuditLogging
    'Core.middleware.OrgContextMiddleware',      # Resolves user org-unit & assigns to request
    'Core.middleware.AccessScopeMiddleware',     # Computes data visibility scope
    'Core.middleware.MailboxContextMiddleware',  # For messaging endpoints
    'Core.middleware.AuditLoggingMiddleware',    # Logs all mutations (should be last)
    # Thread-local request helper for audit signals
    'Auth.middleware.RequestMiddleware',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

ROOT_URLCONF = 'Core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DB_ENGINE = config('DB_ENGINE', default='django.db.backends.sqlite3')

if DB_ENGINE == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': DB_ENGINE,
            'NAME':     config('DB_NAME', default='prison_pms'),
            'USER':     config('DB_USER', default='postgres'),
            'PASSWORD': config('DB_PASSWORD', default='postgres'),
            'HOST':     config('DB_HOST', default='localhost'),
            'PORT':     config('DB_PORT', default='5432'),
            # Connection pooling
            'CONN_MAX_AGE': config('DB_CONN_MAX_AGE', default=600, cast=int),
            'OPTIONS': {
                'connect_timeout': 10,
            }
        }
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Africa/Harare timezone (Zimbabwe prison system location)
TIME_ZONE = config('TIMEZONE', default='Africa/Harare')

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# ==================================================
# REST FRAMEWORK CONFIGURATION
# ==================================================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'Core.filters.OrgUnitAccessFilterBackend',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 50,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ),
}


# ==================================================
# JWT CONFIGURATION
# ==================================================
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    
    'JTI_CLAIM': 'jti',
}


# ==================================================
# CORS CONFIGURATION (Frontend-Backend Communication)
# ==================================================
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",  # Vite default port
#     "http://localhost:3000",  # Alternative React port
#     "http://localhost:8080",  # Frontend dev server (configured in vite.config.ts)
#     "http://127.0.0.1:5173",
#     "http://127.0.0.1:3000",
#     "http://127.0.0.1:8080",
DEFAULT_CORS_ORIGINS = 'http://localhost:8080,http://127.0.0.1:8080,http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000'
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=False, cast=bool)
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', cast=Csv(), default=DEFAULT_CORS_ORIGINS)
CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]


# ==================================================
# SECURITY SETTINGS (Phase 0: Foundation)
# ==================================================
SECURE_BROWSER_XSS_FILTER = True

# Cookie security (HTTPS in production)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=False, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=False, cast=bool)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
CSRF_COOKIE_SAMESITE = 'Strict'

# Session timeout (8 hours)
SESSION_COOKIE_AGE = config('SESSION_COOKIE_AGE', default=28800, cast=int)

# Production security headers (enable with HTTPS)
if not DEBUG:
    # Force HTTPS
    SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=False, cast=bool)
    SECURE_HSTS_SECONDS = config('SECURE_HSTS_SECONDS', default=31536000, cast=int)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# ==================================================
# LOGGING CONFIGURATION (Phase 0: Audit Trail Foundation)
# ==================================================
# Ensure logs directory exists
import logging.handlers
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'audit': {
            'format': '{asctime} | {user} | {org_unit} | {action} | {resource} | {status} | {ip}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'django_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'django.log',
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
        'audit_file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'audit.log',
            'maxBytes': 10485760,  # 10 MB
            'backupCount': 30,  # ~30 days of logs
            'formatter': 'audit',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'django_file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['django_file'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'Auth': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'audit': {
            'handlers': ['audit_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'Reception': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'Health': {
            'handlers': ['console', 'django_file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ==================================================
# ORGANIZATION HIERARCHY CONFIGURATION (Phase 1+)
# ==================================================
# These settings guide the setup wizard for building the national → provincial → station hierarchy

# National HQ initialization (Phase 1 setup wizard will use these defaults)
INITIAL_ORG_NAME = config('INITIAL_ORG_NAME', default='National Headquarters')
INITIAL_ORG_CODE = config('INITIAL_ORG_CODE', default='NAT_HQ_001')
INITIAL_ORG_TYPE = 'NATIONAL_HQ'

# System setup state configuration
SYSTEM_SETUP_TIMEOUT_HOURS = config('SYSTEM_SETUP_TIMEOUT_HOURS', default=72, cast=int)

# Org unit capacity targets
ORG_CAPACITY = {
    'national_hq': {'users': 50, 'departments': 8},
    'provincial_hq': {'users': 30, 'departments': 8, 'count': 10},
    'station': {'users': 25, 'departments': 8, 'count': 120},
}

# Fixed departments (seeded during setup)
FIXED_DEPARTMENTS = [
    {'code': 'RECEPTION', 'name': 'Reception / Admissions'},
    {'code': 'HEALTH', 'name': 'Health / Medical Services'},
    {'code': 'HUMAN_RESOURCES', 'name': 'Human Resources / Personnel'},
    {'code': 'STORES', 'name': 'Stores / Logistics'},
    {'code': 'FARMS', 'name': 'Farms / Production'},
    {'code': 'FINANCE', 'name': 'Finance / Administration'},
    {'code': 'SECURITY', 'name': 'Security / Disciplinary'},
    {'code': 'ADMIN', 'name': 'General Administration'},
]

# Data exposure policy configuration
DATA_EXPOSURE_CONFIG = {
    'default_visibility_level': 'SUMMARY',  # SUMMARY, DETAIL_READ_ONLY, CUSTOM
    'policy_approval_required': True,
    'auto_expire_days': None,  # Policies never auto-expire unless explicitly set
}


# ==================================================
# COMPLIANCE & AUDIT CONFIGURATION
# ==================================================
# Audit trail retention (7 years = ~2555 days)
AUDIT_RETENTION_DAYS = config('AUDIT_RETENTION_DAYS', default=2555, cast=int)

# Message retention (1 year)
MESSAGE_RETENTION_DAYS = config('MESSAGE_RETENTION_DAYS', default=365, cast=int)

# Maximum thread participants for messaging
MAX_THREAD_RECIPIENTS = config('MAX_THREAD_RECIPIENTS', default=50, cast=int)

# File upload configuration
FILE_UPLOAD_MAX_MEMORY_SIZE = config('FILE_UPLOAD_MAX_MEMORY_SIZE', default=104857600, cast=int)  # 100MB
ALLOWED_UPLOAD_EXTENSIONS = ['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx', 'xls', 'xlsx']

