# Generated by Django 5.2.11 on 2026-02-28 09:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('issuing_authority', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'marital_status',
            },
        ),
        migrations.CreateModel(
            name='OffenceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('severity_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'offence_type',
            },
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('service_number', models.CharField(max_length=8, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Service number must be in the format 2934823Z', regex='^[0-9]{7}[A-Z]$')])),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{6,7}\\s?[A-Z]\\s?[0-9]{2}$', 'Invalid National ID format')])),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('date_of_attestation', models.DateField()),
                ('date_of_retirement', models.DateField(blank=True, null=True)),
                ('current_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('DISMISSED', 'Dismissed'), ('DECEASED', 'Deceased')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'officer',
                'ordering': ['surname', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'qualification_type',
            },
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rank_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'rank',
                'ordering': ['rank_level'],
            },
        ),
        migrations.CreateModel(
            name='Dependant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('national_id', models.CharField(blank=True, max_length=20, null=True)),
                ('birth_certificate', models.FileField(upload_to='officers/dependants/')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='HumanResources.officer')),
            ],
            options={
                'db_table': 'dependant',
            },
        ),
        migrations.CreateModel(
            name='ChargeSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_date', models.DateField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONCLUDED', 'Concluded'), ('WITHDRAWN', 'Withdrawn')], max_length=20)),
                ('document', models.FileField(upload_to='officers/charges/')),
                ('offence_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HumanResources.offencetype')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_sheets', to='HumanResources.officer')),
            ],
            options={
                'db_table': 'charge_sheet',
            },
        ),
        migrations.CreateModel(
            name='OfficerAuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='HumanResources.officer')),
            ],
            options={
                'db_table': 'officer_audit_trail',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OfficerCourseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('result', models.CharField(max_length=50)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='officers/courses/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HumanResources.course')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='HumanResources.officer')),
            ],
            options={
                'db_table': 'officer_course_history',
            },
        ),
        migrations.CreateModel(
            name='OfficerDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='officers/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='HumanResources.officer')),
            ],
            options={
                'db_table': 'officer_document',
            },
        ),
        migrations.CreateModel(
            name='OfficerStationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField()),
                ('date_transferred', models.DateField(blank=True, null=True)),
                ('posted_by', models.CharField(max_length=100)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_history', to='HumanResources.officer')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.station')),
            ],
            options={
                'db_table': 'officer_station_history',
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='OfficerQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('date_awarded', models.DateField()),
                ('certificate', models.FileField(upload_to='officers/qualifications/')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='HumanResources.officer')),
                ('qualification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HumanResources.qualificationtype')),
            ],
            options={
                'db_table': 'officer_qualification',
            },
        ),
        migrations.CreateModel(
            name='OfficerRankHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('change_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('DEMOTION', 'Demotion'), ('ACTING', 'Acting')], max_length=20)),
                ('authority', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_history', to='HumanResources.officer')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HumanResources.rank')),
            ],
            options={
                'db_table': 'officer_rank_history',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_type', models.CharField(max_length=100)),
                ('sentence_date', models.DateField()),
                ('duration_months', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('charge_sheet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentence', to='HumanResources.chargesheet')),
            ],
            options={
                'db_table': 'sentence',
            },
        ),
    ]
