# Generated by Django 5.2.11 on 2026-05-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HumanResources', '0002_add_org_unit_ownership'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='officerstationhistory',
            name='officerstationhistory_org_date_idx',
        ),
    ]
