# Generated by Django 5.2.11 on 2026-08-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporttemplate",
            name="filters",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of filter conditions (Where clause)",
                null=True,
            ),
        ),
    ]
