# Generated by Django 5.2.11 on 2026-02-28 09:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_type', models.CharField(choices=[('NEW_ADMISSION', 'New Admission'), ('TRANSFER', 'Transfer')], default='New Admission', max_length=20)),
                ('prison_number', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{4}/\\d{2}$', 'Prison number must be in the format 0001/25')])),
                ('crb_number', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(blank=True, max_length=100, null=True)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{2}-[0-9]{6,7}\\s?[A-Z]\\s?[0-9]{2}$', 'Invalid National ID format')])),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=20, null=True)),
                ('nationality', models.CharField(max_length=50)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
                ('current_status', models.CharField(choices=[('IN_CUSTODY', 'In Custody'), ('TRANSFERRED', 'Transferred'), ('ESCAPED', 'Escaped'), ('DISCHARGED', 'Discharged'), ('DECEASED', 'Deceased')], default='IN_CUSTODY', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inmate',
                'ordering': ['-admission_date'],
            },
        ),
        migrations.CreateModel(
            name='EscapeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escape_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('recaptured', models.BooleanField(default=False)),
                ('recapture_date', models.DateField(blank=True, null=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escape_history', to='Reception.inmate')),
            ],
            options={
                'db_table': 'escape_history',
            },
        ),
        migrations.CreateModel(
            name='InmateAuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='Reception.inmate')),
            ],
            options={
                'db_table': 'inmate_audit_trail',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InmateClassificationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('COND', 'Condemned'), ('PUSOD', 'PUSOD')], max_length=20)),
                ('effective_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classification_history', to='Reception.inmate')),
            ],
            options={
                'db_table': 'inmate_classification_history',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='InmateDisciplinaryHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence', models.CharField(max_length=200)),
                ('punishment', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_history', to='Reception.inmate')),
            ],
            options={
                'db_table': 'inmate_disciplinary_history',
            },
        ),
        migrations.CreateModel(
            name='InmateDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='inmate/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Reception.inmate')),
            ],
            options={
                'db_table': 'inmate_document',
            },
        ),
        migrations.CreateModel(
            name='InmatePropertyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_number', models.CharField(max_length=50)),
                ('items_description', models.TextField()),
                ('cash_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_logged', models.DateField()),
                ('date_released', models.DateField(blank=True, null=True)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_history', to='Reception.inmate')),
            ],
            options={
                'db_table': 'inmate_property_history',
            },
        ),
        migrations.CreateModel(
            name='InmateStationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_admitted', models.DateField()),
                ('date_released', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(max_length=50)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_history', to='Reception.inmate')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Auth.station')),
            ],
            options={
                'db_table': 'inmate_station_history',
                'ordering': ['-date_admitted'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='Reception.inmate')),
            ],
            options={
                'db_table': 'next_of_kin',
            },
        ),
        migrations.CreateModel(
            name='Offence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offence_description', models.TextField()),
                ('court', models.CharField(max_length=100)),
                ('date_charged', models.DateField()),
                ('Offence_status', models.CharField(choices=[('UNCONVICTED', 'Unconvicted'), ('CONVICTED', 'Convicted')], default='UNCONVICTED', max_length=20)),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offences', to='Reception.inmate')),
            ],
            options={
                'db_table': 'offence',
            },
        ),
        migrations.CreateModel(
            name='CourtSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(help_text='Date when the court session took place')),
                ('outcome', models.CharField(blank=True, help_text='Outcome (e.g., Remanded, Bail Denied)', max_length=200, null=True)),
                ('next_court_date', models.DateField(help_text='The new court date set during this session')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('offence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_sessions', to='Reception.offence')),
            ],
            options={
                'db_table': 'court_session',
                'ordering': ['-session_date'],
            },
        ),
        migrations.CreateModel(
            name='Convicted',
            fields=[
                ('convicted_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_sentence', models.DateField()),
                ('sentence', models.PositiveIntegerField(help_text='Sentence duration in months')),
                ('sentence_start_date', models.DateField(blank=True, null=True)),
                ('sentence_end_date', models.DateField(blank=True, null=True)),
                ('prison_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convictions', to='Reception.inmate')),
                ('offence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conviction', to='Reception.offence')),
            ],
            options={
                'db_table': 'convicted',
            },
        ),
        migrations.CreateModel(
            name='ReleaseHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_effective_sentence', models.PositiveIntegerField(help_text='Total sentence duration in months')),
                ('remission', models.DecimalField(blank=True, decimal_places=2, help_text='Remission in months', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('earliest_date_of_release', models.DateField()),
                ('inmate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='release_history', to='Reception.inmate')),
            ],
            options={
                'db_table': 'release_history',
            },
        ),
        migrations.CreateModel(
            name='Restitution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restitution_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('restitution_date', models.DateField()),
                ('alternative_restitution_sentence', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('waived', 'Waived')], default='pending', max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='inmate/restitution_receipts/')),
                ('inmate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restitution', to='Reception.inmate')),
                ('offence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restitutions', to='Reception.offence')),
            ],
            options={
                'db_table': 'restitution',
            },
        ),
        migrations.CreateModel(
            name='RestitutionExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_extended', models.DateField(auto_now_add=True, help_text='Date when the extension was granted')),
                ('previous_date', models.DateField(help_text='The deadline before this extension')),
                ('new_date', models.DateField(help_text='The new extended deadline')),
                ('reason', models.TextField(help_text='Reason for the extension')),
                ('restitution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='Reception.restitution')),
            ],
            options={
                'db_table': 'restitution_extension',
                'ordering': ['-date_extended'],
            },
        ),
        migrations.CreateModel(
            name='Unconvicted',
            fields=[
                ('unconvicted_id', models.AutoField(primary_key=True, serialize=False)),
                ('next_court_date', models.DateField(blank=True, null=True)),
                ('arrest_date', models.DateField(blank=True, null=True)),
                ('bail_date', models.DateField(blank=True, null=True)),
                ('remand_start_date', models.DateField(blank=True, help_text='Date remanded into custody', null=True)),
                ('remand_end_date', models.DateField(blank=True, help_text='Date remand ended (conviction or release)', null=True)),
                ('offence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unconviction', to='Reception.offence')),
                ('prison_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unconvictions', to='Reception.inmate')),
            ],
            options={
                'db_table': 'unconvicted',
            },
        ),
    ]
