# Generated by Django 5.2.11 on 2026-05-12 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_remove_userassignment_unique_active_primary_assignment_per_user_and_more'),
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmate',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='chief',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='educational_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='headman',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='inmate_image',
            field=models.ImageField(blank=True, null=True, upload_to='inmate/photos/'),
        ),
        migrations.AddField(
            model_name='inmate',
            name='is_first_time_offender',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inmate',
            name='owner_org_unit',
            field=models.ForeignKey(blank=True, help_text='Organization unit that owns/admits this inmate. Used for data isolation.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inmates', to='Auth.orgunit'),
        ),
        migrations.AddField(
            model_name='inmate',
            name='race',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
