# Generated by Django 5.2.11 on 2026-06-13 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reception", "0002_inmate_address_inmate_chief_inmate_district_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="convicted",
            name="date_of_sentence",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="convicted",
            name="sentence",
            field=models.PositiveIntegerField(
                blank=True, help_text="Sentence duration in months", null=True
            ),
        ),
        migrations.CreateModel(
            name="SentenceGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_sentence", models.DateField()),
                (
                    "duration_months",
                    models.PositiveIntegerField(
                        help_text="Sentence duration in months"
                    ),
                ),
                ("is_concurrent", models.BooleanField(default=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "inmate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentence_groups",
                        to="Reception.inmate",
                    ),
                ),
            ],
            options={
                "db_table": "sentence_group",
                "ordering": ["-date_of_sentence"],
            },
        ),
        migrations.AddField(
            model_name="convicted",
            name="sentence_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="convictions",
                to="Reception.sentencegroup",
            ),
        ),
    ]
