# Generated by Django 5.2.11 on 2026-06-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reception", "0003_alter_convicted_date_of_sentence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convicted",
            name="effective_sentence_days",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="convicted",
            name="remission_days",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="convicted",
            name="sentence_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="convicted",
            name="sentence_months",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="convicted",
            name="sentence_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="active_edr",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="active_odr",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="edr_restitution_paid",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="edr_standard",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="odr_restitution_paid",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="odr_standard",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="total_remission_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="total_sentences_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restitution",
            name="restitution_sentence_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restitution",
            name="restitution_sentence_days_total",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name="restitution",
            name="restitution_sentence_months",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="restitution",
            name="restitution_sentence_years",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="releasehistory",
            name="earliest_date_of_release",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="releasehistory",
            name="total_effective_sentence",
            field=models.PositiveIntegerField(
                blank=True, help_text="Total sentence duration in months", null=True
            ),
        ),
    ]
