# Generated by Django 5.2.11 on 2026-06-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0004_convicted_effective_sentence_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convicted',
            name='effective_sentence_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='convicted',
            name='remission_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='releasehistory',
            name='earliest_date_of_release',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='releasehistory',
            name='total_effective_sentence',
            field=models.PositiveIntegerField(help_text='Total sentence duration in months'),
        ),
        migrations.AlterField(
            model_name='restitution',
            name='restitution_sentence_days_total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
