# Generated by Django 5.2.11 on 2026-06-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reception", "0005_alter_convicted_effective_sentence_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="inmate",
            name="admission_status",
            field=models.CharField(
                choices=[
                    ("PENDING_HEALTH_ASSESSMENT", "Pending Health Assessment"),
                    ("PENDING_ADMIN_APPROVAL", "Pending Admin Approval"),
                    ("ADMISSION_CONFIRMED", "Admission Confirmed"),
                ],
                default="PENDING_HEALTH_ASSESSMENT",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="inmateclassificationhistory",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="releasehistory",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Approval"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
