# Generated by Django 5.2.11 on 2026-06-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reception", "0006_inmate_admission_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchivedDischarge",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("archive_date", models.DateTimeField(auto_now_add=True)),
                ("original_discharge_date", models.DateField()),
                (
                    "inmate_prison_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("offence_description", models.TextField()),
                ("discharge_reason", models.CharField(max_length=50)),
                (
                    "compressed_data",
                    models.JSONField(
                        help_text="Full JSON snapshot of the original discharge and offence records"
                    ),
                ),
            ],
            options={
                "db_table": "archived_discharge",
                "ordering": ["-original_discharge_date"],
            },
        ),
        migrations.AlterField(
            model_name="courtsession",
            name="next_court_date",
            field=models.DateField(
                blank=True,
                help_text="The new court date set during this session (required if remanded)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courtsession",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("REMANDED", "Remanded (Next Court Date Set)"),
                    ("CONVICTED", "Convicted / Sentenced"),
                    ("DISCHARGED", "Discharged"),
                ],
                default="REMANDED",
                help_text="Outcome of the session",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="offence",
            name="Offence_status",
            field=models.CharField(
                choices=[
                    ("UNCONVICTED", "Unconvicted"),
                    ("CONVICTED", "Convicted"),
                    ("DISCHARGED", "Discharged"),
                ],
                default="UNCONVICTED",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Discharged",
            fields=[
                ("discharged_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "discharge_reason",
                    models.CharField(
                        choices=[
                            ("BAIL", "Bail"),
                            ("FINE", "Fine"),
                            ("ACQUITTED", "Not guilty and acquitted"),
                            ("WITHDRAWN", "Withdrawn before/after plea"),
                            ("COMMUNITY_SERVICE", "Community service"),
                            ("SENTENCE_EXPIRES", "Sentence expires"),
                            ("AMNESTY", "Amnesty"),
                        ],
                        max_length=50,
                    ),
                ),
                ("discharge_date", models.DateField()),
                ("remarks", models.TextField(blank=True, null=True)),
                (
                    "offence",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge",
                        to="Reception.offence",
                    ),
                ),
                (
                    "prison_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharges",
                        to="Reception.inmate",
                    ),
                ),
            ],
            options={
                "db_table": "discharged",
            },
        ),
        migrations.CreateModel(
            name="ReleaseWorkflow",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED_BY_RECEPTION", "Proposed by Reception"),
                            ("HEALTH_ASSESSED", "Health Assessed"),
                            ("APPROVED_BY_ADMIN", "Approved by Admin (Released)"),
                        ],
                        default="PROPOSED_BY_RECEPTION",
                        max_length=30,
                    ),
                ),
                ("proposed_date", models.DateTimeField(auto_now_add=True)),
                ("health_assessment_date", models.DateTimeField(blank=True, null=True)),
                ("health_remarks", models.TextField(blank=True, null=True)),
                ("approved_date", models.DateTimeField(blank=True, null=True)),
                ("admin_remarks", models.TextField(blank=True, null=True)),
                (
                    "inmate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="release_workflows",
                        to="Reception.inmate",
                    ),
                ),
            ],
            options={
                "db_table": "release_workflow",
                "ordering": ["-proposed_date"],
            },
        ),
    ]
