# Generated by Django 5.2.11 on 2026-07-06 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Reception",
            "0007_archiveddischarge_alter_courtsession_next_court_date_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="courtsession",
            name="warrant_document",
            field=models.FileField(
                blank=True,
                help_text="Document/Warrant requesting the inmate to attend court",
                null=True,
                upload_to="court_warrants/",
            ),
        ),
        migrations.AlterField(
            model_name="courtsession",
            name="next_court_date",
            field=models.DateField(
                blank=True,
                help_text="The new court date set during this session (required if remanded or scheduled)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="courtsession",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled / Pending"),
                    ("REMANDED", "Remanded (Next Court Date Set)"),
                    ("CONVICTED", "Convicted / Sentenced"),
                    ("DISCHARGED", "Discharged"),
                ],
                default="SCHEDULED",
                help_text="Outcome of the session",
                max_length=20,
            ),
        ),
    ]
