# Generated by Django 5.2.11 on 2026-07-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reception", "0008_courtsession_warrant_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="convicted",
            name="fine_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="convicted",
            name="has_fine",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="offence",
            name="bail_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="offence",
            name="has_bail",
            field=models.BooleanField(default=False),
        ),
    ]
