# Generated by Django 5.2.11 on 2026-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reception", "0009_convicted_fine_amount_convicted_has_fine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="releaseworkflow",
            name="reception_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="releaseworkflow",
            name="reception_receipt",
            field=models.FileField(
                blank=True, null=True, upload_to="discharge_receipts/"
            ),
        ),
    ]
