# Generated by Django 5.2.11 on 2026-08-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reception", "0010_releaseworkflow_reception_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courtsession",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("SCHEDULED", "Scheduled / Pending"),
                    ("REMANDED", "Remanded (Next Court Date Set)"),
                    ("CONVICTED", "Convicted / Sentenced"),
                    ("DISCHARGED", "Discharged"),
                    ("RESTITUTION_SETTLED", "Restitution Settled (Closed)"),
                ],
                default="SCHEDULED",
                help_text="Outcome of the session",
                max_length=20,
            ),
        ),
    ]
