# Generated by Django 5.2.11 on 2026-08-12 19:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Reception", "0011_alter_courtsession_outcome"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestitutionPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("receipt_number", models.CharField(max_length=100)),
                (
                    "receipt_file",
                    models.FileField(
                        blank=True, null=True, upload_to="inmate/restitution_receipts/"
                    ),
                ),
                ("payment_date", models.DateTimeField(auto_now_add=True)),
                ("recorded_by", models.CharField(max_length=100)),
                (
                    "restitution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="Reception.restitution",
                    ),
                ),
            ],
            options={
                "db_table": "restitution_payment",
                "ordering": ["-payment_date"],
            },
        ),
    ]
