# Generated by Django 5.2.11 on 2026-08-17 20:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0005_alter_auditlog_station"),
        ("Reception", "0012_restitutionpayment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="releaseworkflow",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROPOSED_BY_RECEPTION", "Proposed by Reception"),
                    ("HEALTH_ASSESSED", "Health Assessed"),
                    ("APPROVED_BY_ADMIN", "Approved by Admin (Released)"),
                    ("REJECTED", "Rejected"),
                ],
                default="PROPOSED_BY_RECEPTION",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("capacity", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "reception_cell",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LockupRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                (
                    "total_count",
                    models.PositiveIntegerField(help_text="Cached sum of cell counts"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("CORRECTED", "Corrected"),
                            ("VOIDED", "Voided"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Auth.userassignment",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lockups",
                        to="Auth.orgunit",
                    ),
                ),
            ],
            options={
                "db_table": "reception_lockup_record",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="UnlockRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("time", models.TimeField(default=django.utils.timezone.now)),
                (
                    "total_count",
                    models.PositiveIntegerField(help_text="Cached sum of cell counts"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("CORRECTED", "Corrected"),
                            ("VOIDED", "Voided"),
                        ],
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Auth.userassignment",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="unlocks",
                        to="Auth.orgunit",
                    ),
                ),
            ],
            options={
                "db_table": "reception_unlock_record",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="Yard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="yards",
                        to="Auth.orgunit",
                    ),
                ),
            ],
            options={
                "db_table": "reception_yard",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="UnlockCellCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yard_name_snapshot", models.CharField(max_length=100)),
                ("cell_name_snapshot", models.CharField(max_length=100)),
                ("count", models.PositiveIntegerField()),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="Reception.cell"
                    ),
                ),
                (
                    "unlock_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_counts",
                        to="Reception.unlockrecord",
                    ),
                ),
                (
                    "yard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="Reception.yard"
                    ),
                ),
            ],
            options={
                "db_table": "reception_unlock_cell_count",
            },
        ),
        migrations.CreateModel(
            name="LockupCellCount",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yard_name_snapshot", models.CharField(max_length=100)),
                ("cell_name_snapshot", models.CharField(max_length=100)),
                ("count", models.PositiveIntegerField()),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="Reception.cell"
                    ),
                ),
                (
                    "lockup_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_counts",
                        to="Reception.lockuprecord",
                    ),
                ),
                (
                    "yard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="Reception.yard"
                    ),
                ),
            ],
            options={
                "db_table": "reception_lockup_cell_count",
            },
        ),
        migrations.AddField(
            model_name="cell",
            name="yard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cells",
                to="Reception.yard",
            ),
        ),
    ]
