# Generated by Django 5.2.11 on 2026-08-18 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0012_restitutionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='releaseworkflow',
            name='status',
            field=models.CharField(choices=[('PROPOSED_BY_RECEPTION', 'Proposed by Reception'), ('HEALTH_ASSESSED', 'Health Assessed'), ('APPROVED_BY_ADMIN', 'Approved by Admin (Released)'), ('REJECTED', 'Rejected')], default='PROPOSED_BY_RECEPTION', max_length=30),
        ),
    ]
