# Generated by Django 5.2.11 on 2026-08-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reception', '0013_alter_releaseworkflow_status'),
        ('Reception', '0013_alter_releaseworkflow_status_cell_lockuprecord_and_more'),
    ]

    operations = [
    ]
