# Generated by Django 5.2.11 on 2026-05-13 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Messaging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="folder",
            field=models.CharField(
                default="INBOX", help_text="INBOX/OUTBOX/DRAFT", max_length=16
            ),
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drafts",
                        to="Messaging.mailbox",
                    ),
                ),
            ],
            options={
                "db_table": "messaging_draft",
            },
        ),
    ]
