# Generated by Django 5.2.11 on 2026-02-28 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HumanResources', '0001_initial'),
        ('Stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'animal_type',
            },
        ),
        migrations.CreateModel(
            name='CropCycle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('area_planted_hectares', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'crop_cycle',
            },
        ),
        migrations.CreateModel(
            name='CropType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'crop_type',
            },
        ),
        migrations.CreateModel(
            name='CropInputUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('usage_date', models.DateField(default=django.utils.timezone.now)),
                ('crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.cropcycle')),
                ('input_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stores.inventoryitem')),
            ],
            options={
                'db_table': 'crop_input_usage',
            },
        ),
        migrations.CreateModel(
            name='CropOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_harvested', models.PositiveIntegerField()),
                ('quality_grade', models.CharField(max_length=50)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Farms.cropcycle')),
            ],
            options={
                'db_table': 'crop_output',
            },
        ),
        migrations.AddField(
            model_name='cropcycle',
            name='crop_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farms.croptype'),
        ),
        migrations.CreateModel(
            name='FarmProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
                ('supervising_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HumanResources.officer')),
            ],
            options={
                'db_table': 'farm_project',
            },
        ),
        migrations.CreateModel(
            name='FarmExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farms.farmproject')),
            ],
            options={
                'db_table': 'farm_expense',
            },
        ),
        migrations.AddField(
            model_name='cropcycle',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farms.farmproject'),
        ),
        migrations.CreateModel(
            name='FarmRevenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('buyer', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farms.farmproject')),
            ],
            options={
                'db_table': 'farm_revenue',
            },
        ),
        migrations.CreateModel(
            name='LivestockBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquisition_date', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=100)),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farms.animaltype')),
            ],
            options={
                'db_table': 'livestock_batch',
            },
        ),
        migrations.CreateModel(
            name='LivestockEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('BIRTH', 'Birth'), ('DEATH', 'Death'), ('SALE', 'Sale'), ('SLAUGHTER', 'Slaughter')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('event_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farms.livestockbatch')),
            ],
            options={
                'db_table': 'livestock_event',
            },
        ),
    ]
