# Generated by Django 5.2.11 on 2026-02-28 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auth_role',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'auth_station',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50)),
                ('action', models.CharField(max_length=200)),
                ('module', models.CharField(choices=[('AUTH', 'Authentication'), ('INMATES', 'Inmates'), ('HEALTH', 'Health'), ('STORES', 'Stores'), ('FARMS', 'Farms'), ('HR', 'Human Resources'), ('RBAC', 'Role Management')], max_length=50)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
                ('object_type', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, max_length=10, null=True)),
                ('request_path', models.CharField(blank=True, max_length=500, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='Auth.station')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_log_user_id_79f582_idx'), models.Index(fields=['module', '-timestamp'], name='audit_log_module_a6edcf_idx'), models.Index(fields=['station', '-timestamp'], name='audit_log_station_f1026d_idx'), models.Index(fields=['role', '-timestamp'], name='audit_log_role_06889d_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='Auth.role')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profiles', to='Auth.station')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'indexes': [models.Index(fields=['role', 'station'], name='user_profil_role_id_028414_idx'), models.Index(fields=['is_active'], name='user_profil_is_acti_9f91cc_idx')],
            },
        ),
    ]
