# Generated by Django 5.2.11 on 2026-04-23 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='officer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='system_account', to='HumanResources.officer'),
        ),
    ]
