# Generated by Django 5.2.11 on 2026-05-12 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0003_phase_1_organizational_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userassignment',
            name='unique_active_primary_assignment_per_user',
        ),
        migrations.RenameIndex(
            model_name='dataexposurepolicy',
            new_name='auth_data_e_source__15fcef_idx',
            old_name='auth_data_ex_source_idx',
        ),
        migrations.RenameIndex(
            model_name='dataexposurepolicy',
            new_name='auth_data_e_status_2974c1_idx',
            old_name='auth_data_ex_status_idx',
        ),
        migrations.RenameIndex(
            model_name='dataexposurerecord',
            new_name='auth_data_e_resourc_17c494_idx',
            old_name='auth_data_ex_rec_res_idx',
        ),
        migrations.RenameIndex(
            model_name='orgunit',
            new_name='auth_org_un_unit_ty_69a101_idx',
            old_name='auth_org_un_unit_ty_idx',
        ),
        migrations.RenameIndex(
            model_name='orgunit',
            new_name='auth_org_un_active_89b108_idx',
            old_name='auth_org_un_active_idx',
        ),
        migrations.RenameIndex(
            model_name='orgunit',
            new_name='auth_org_un_code_5cc79b_idx',
            old_name='auth_org_un_code_idx',
        ),
        migrations.RenameIndex(
            model_name='orgunitdepartment',
            new_name='auth_org_un_org_uni_08c5d3_idx',
            old_name='auth_org_un_org_uni_idx',
        ),
        migrations.RenameIndex(
            model_name='orgunitdepartment',
            new_name='auth_org_un_mailbox_d8c7d7_idx',
            old_name='auth_org_un_mailbox_idx',
        ),
        migrations.RenameIndex(
            model_name='userassignment',
            new_name='auth_user_a_user_id_5b1edb_idx',
            old_name='auth_user_as_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='userassignment',
            new_name='auth_user_a_user_id_50cfbb_idx',
            old_name='auth_user_as_user_is_idx',
        ),
        migrations.RenameIndex(
            model_name='userassignment',
            new_name='auth_user_a_org_uni_b949e7_idx',
            old_name='auth_user_as_org_unit_idx',
        ),
        migrations.RenameIndex(
            model_name='userassignment',
            new_name='auth_user_a_org_uni_3ba293_idx',
            old_name='auth_user_as_org_role_idx',
        ),
        migrations.AlterField(
            model_name='dataexposurepolicy',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to='Auth.userassignment'),
        ),
        migrations.AlterField(
            model_name='dataexposurerecord',
            name='exposed_by',
            field=models.ForeignKey(help_text='Admin who exposed record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exposed_records', to='Auth.userassignment'),
        ),
        migrations.AddConstraint(
            model_name='userassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('is_active', True)), fields=('user', 'is_primary'), name='unique_active_primary_assignment_per_user', violation_error_message='User can have only one active primary assignment'),
        ),
    ]
