# Generated by Django 5.2.11 on 2026-05-13 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_remove_userassignment_unique_active_primary_assignment_per_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='Auth.station'),
        ),
    ]
