# Generated by Django 5.2.11 on 2026-02-28 09:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
        ('HumanResources', '0001_initial'),
        ('Reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthAuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'health_audit_trail',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionHealthAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(default=django.utils.timezone.now, help_text='Date of health assessment')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kilograms', max_digits=5, validators=[django.core.validators.MinValueValidator(20)])),
                ('height', models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(100)])),
                ('bmi', models.DecimalField(blank=True, decimal_places=2, help_text='Body Mass Index (auto-calculated)', max_digits=5, null=True)),
                ('comment', models.TextField(blank=True, help_text='General health assessment comments', null=True)),
                ('is_chronic_patient', models.BooleanField(default=False, help_text='Indicates if inmate has chronic conditions requiring ongoing care')),
                ('assessed_by', models.CharField(help_text='Healthcare professional conducting assessment', max_length=100)),
                ('inmate', models.OneToOneField(blank=True, help_text='Inmate undergoing admission assessment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admission_health_assessment', to='Reception.inmate')),
                ('station', models.ForeignKey(help_text='Station where assessment was conducted', on_delete=django.db.models.deletion.PROTECT, to='Auth.station')),
            ],
            options={
                'db_table': 'admission_health_assessment',
                'ordering': ['-assessment_date'],
            },
        ),
        migrations.CreateModel(
            name='MedicalEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(help_text='Name of the medical equipment', max_length=100)),
                ('serial_number', models.CharField(help_text='Unique serial number of the equipment', max_length=100, unique=True)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('BROKEN', 'Broken')], help_text='Current condition of the equipment', max_length=50)),
                ('location', models.CharField(help_text='Physical location of the equipment', max_length=100)),
                ('station', models.ForeignKey(help_text='Station where equipment is located', on_delete=django.db.models.deletion.PROTECT, to='Auth.station')),
            ],
            options={
                'db_table': 'medical_equipment',
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_by', models.CharField(help_text='Person using the equipment', max_length=100)),
                ('usage_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of usage')),
                ('purpose', models.TextField(help_text='Purpose of equipment usage')),
                ('returned', models.BooleanField(default=False, help_text='Whether equipment has been returned')),
                ('return_date', models.DateTimeField(blank=True, help_text='Date and time of return', null=True)),
                ('equipment', models.ForeignKey(help_text='Equipment being used', on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='Health.medicalequipment')),
            ],
            options={
                'db_table': 'equipment_usage_log',
                'ordering': ['-usage_date'],
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(help_text='Name of the medication', max_length=200)),
                ('dosage_form', models.CharField(help_text='Form of medication (tablet, syrup, injection, etc.)', max_length=50)),
                ('strength', models.CharField(help_text='Strength/dosage of medication', max_length=50)),
                ('unit_of_measure', models.CharField(help_text='Unit of measurement (mg, ml, units, etc.)', max_length=50)),
                ('reorder_level', models.PositiveIntegerField(help_text='Minimum stock level before reorder', validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'medicine',
                'unique_together': {('medicine_name', 'strength', 'dosage_form')},
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_type', models.CharField(choices=[('INMATE', 'Inmate'), ('OFFICER', 'Officer'), ('DEPENDENT', 'Dependent'), ('COMMUNITY_MEMBER', 'Community Member'), ('EX_SERVICE_MEMBER', 'Ex-Service Member')], help_text='Type of patient for appropriate data sourcing', max_length=20)),
                ('full_name', models.CharField(blank=True, help_text='Full name for community/ex-service patients', max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, help_text='Date of birth for age calculation', null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], help_text='Gender for community/ex-service patients', max_length=10, null=True)),
                ('address', models.TextField(blank=True, help_text='Address for chronic patient medication delivery', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Contact number for medication follow-up', max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?[\\d\\s\\-\\(\\)]+$', 'Invalid phone number format')])),
                ('service_number', models.CharField(blank=True, help_text='Service number for ex-service members', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dependent', models.ForeignKey(blank=True, help_text='Reference to dependent record (for dependent patients)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='HumanResources.dependant')),
                ('inmate', models.ForeignKey(blank=True, help_text='Reference to inmate record (for inmate patients)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='Reception.inmate')),
                ('officer', models.ForeignKey(blank=True, help_text='Reference to officer record (for officer patients)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='health_records', to='HumanResources.officer')),
                ('station', models.ForeignKey(help_text='Station for data isolation', on_delete=django.db.models.deletion.PROTECT, to='Auth.station')),
            ],
            options={
                'db_table': 'patient',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutPatientVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now, help_text='Date of OPD visit')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Body temperature in Celsius', max_digits=4, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MinValueValidator(45)])),
                ('blood_pressure', models.CharField(help_text='Blood pressure reading (e.g., 120/80)', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, help_text='Current weight in kilograms', max_digits=5, validators=[django.core.validators.MinValueValidator(20)])),
                ('problem', models.TextField(help_text="Patient's reported problem/symptoms")),
                ('duration', models.CharField(help_text='Duration of symptoms (e.g., 3 days, 2 weeks)', max_length=100)),
                ('diagnosis', models.TextField(help_text='Medical diagnosis')),
                ('treatment', models.TextField(help_text='Prescribed treatment plan')),
                ('referral', models.TextField(blank=True, help_text='Referral to specialist or other facility if required', null=True)),
                ('attended_by', models.CharField(help_text='Healthcare professional attending the visit', max_length=100)),
                ('follow_up_required', models.BooleanField(default=False, help_text='Indicates if follow-up visit is needed')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes or observations', null=True)),
                ('station', models.ForeignKey(help_text='Station where visit occurred', on_delete=django.db.models.deletion.PROTECT, to='Auth.station')),
                ('patient', models.ForeignKey(help_text='Patient receiving OPD consultation', on_delete=django.db.models.deletion.CASCADE, related_name='opd_visits', to='Health.patient')),
            ],
            options={
                'db_table': 'outpatient_visit',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='MentalHealthVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(default=django.utils.timezone.now, help_text='Date of mental health assessment')),
                ('place_of_reference', models.CharField(help_text='Location or source of referral', max_length=200)),
                ('reason', models.TextField(help_text='Reason for mental health consultation')),
                ('outcome', models.TextField(help_text='Outcome of the mental health assessment/treatment')),
                ('attended_by', models.CharField(help_text='Mental health professional attending', max_length=100)),
                ('follow_up_required', models.BooleanField(default=False, help_text='Indicates if follow-up is needed')),
                ('remarks', models.TextField(blank=True, help_text='Additional clinical notes', null=True)),
                ('station', models.ForeignKey(help_text='Station where consultation occurred', on_delete=django.db.models.deletion.PROTECT, to='Auth.station')),
                ('patient', models.ForeignKey(help_text='Patient receiving mental health consultation', on_delete=django.db.models.deletion.CASCADE, related_name='mental_health_visits', to='Health.patient')),
            ],
            options={
                'db_table': 'mental_health_visit',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='ChronicPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_collection_date', models.DateField(help_text='Date when medication was collected')),
                ('medication_types', models.TextField(help_text='Types of medication prescribed (comma-separated)')),
                ('quantity_collected', models.TextField(help_text='Quantity of each medication collected')),
                ('registered_by', models.CharField(help_text='Healthcare professional registering the patient', max_length=100)),
                ('registration_date', models.DateField(default=django.utils.timezone.now, help_text='Date of registration in chronic patient program')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes on condition management', null=True)),
                ('station', models.ForeignKey(help_text='Station managing the chronic patient', on_delete=django.db.models.deletion.PROTECT, to='Auth.station')),
                ('patient', models.OneToOneField(help_text='Patient with chronic condition', on_delete=django.db.models.deletion.CASCADE, related_name='chronic_patient_record', to='Health.patient')),
            ],
            options={
                'db_table': 'chronic_patient',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='StockCardEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateField(default=django.utils.timezone.now, help_text='Date of stock transaction')),
                ('received_from', models.CharField(blank=True, help_text='Source of received medication', max_length=200, null=True)),
                ('quantity_received', models.PositiveIntegerField(default=0, help_text='Quantity of medication received')),
                ('issued_to', models.CharField(blank=True, help_text='Recipient of issued medication', max_length=200, null=True)),
                ('quantity_issued', models.PositiveIntegerField(default=0, help_text='Quantity of medication issued')),
                ('balance_brought_forward', models.PositiveIntegerField(help_text='Stock balance from previous entry')),
                ('adjustment', models.IntegerField(default=0, help_text='Stock adjustments (positive or negative)')),
                ('losses', models.PositiveIntegerField(default=0, help_text='Quantity lost or damaged')),
                ('balance', models.PositiveIntegerField(help_text='Current stock balance after transaction')),
                ('issue_voucher', models.FileField(blank=True, help_text='Uploaded issue voucher for received stock', null=True, upload_to='health/stock_vouchers/')),
                ('remarks', models.TextField(blank=True, help_text='Additional notes on the transaction', null=True)),
                ('recorded_by', models.CharField(help_text='Person recording the entry', max_length=100)),
                ('medicine', models.ForeignKey(help_text='Medication being tracked', on_delete=django.db.models.deletion.PROTECT, related_name='stock_entries', to='Health.medicine')),
                ('station', models.ForeignKey(help_text='Station where stock is managed', on_delete=django.db.models.deletion.PROTECT, to='Auth.station')),
            ],
            options={
                'db_table': 'stock_card_entry',
                'ordering': ['medicine', '-entry_date'],
                'unique_together': {('medicine', 'entry_date')},
            },
        ),
    ]
