# Generated by Django 5.2.11 on 2026-05-12 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Health', '0002_add_org_unit_ownership'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='admissionhealthassessment',
            name='admission_assessment_org_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='patient',
            name='patient_owner_org_type_idx',
        ),
    ]
