# Generated by Django 5.2.11 on 2026-06-25 08:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0005_alter_auditlog_station"),
        (
            "Health",
            "0003_remove_admissionhealthassessment_admission_assessment_org_date_idx_and_more",
        ),
        ("Reception", "0006_inmate_admission_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DischargeHealthAssessment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Date of health assessment",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Weight in kilograms",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(20)],
                    ),
                ),
                (
                    "health_status",
                    models.CharField(
                        choices=[
                            ("HEALTHY", "Healthy / Fit for Discharge"),
                            (
                                "NEEDS_CARE",
                                "Requires ongoing medical care post-discharge",
                            ),
                            ("CRITICAL", "Critical / Unfit for standard discharge"),
                        ],
                        default="HEALTHY",
                        max_length=50,
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="General health assessment comments",
                        null=True,
                    ),
                ),
                (
                    "assessed_by",
                    models.CharField(
                        help_text="Healthcare professional conducting assessment",
                        max_length=100,
                    ),
                ),
                (
                    "inmate",
                    models.OneToOneField(
                        help_text="Inmate undergoing discharge assessment",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_health_assessment",
                        to="Reception.inmate",
                    ),
                ),
                (
                    "owner_org_unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization unit where this assessment was conducted.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discharge_assessments",
                        to="Auth.orgunit",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        help_text="Station where assessment was conducted",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="Auth.station",
                    ),
                ),
            ],
            options={
                "db_table": "discharge_health_assessment",
                "ordering": ["-assessment_date"],
            },
        ),
    ]
