# Generated by Django 5.2.11 on 2026-02-28 09:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HumanResources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('is_returnable', models.BooleanField(default=False)),
                ('requires_expiry', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'inventory_item',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_ration_category', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'store_item_category',
            },
        ),
        migrations.CreateModel(
            name='FeedingSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SUPPER', 'Supper')], max_length=10)),
                ('feeding_date', models.DateField(default=django.utils.timezone.now)),
                ('inmate_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HumanResources.officer')),
            ],
            options={
                'db_table': 'feeding_session',
                'unique_together': {('meal_type', 'feeding_date')},
            },
        ),
        migrations.CreateModel(
            name='FeedingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.DecimalField(decimal_places=2, max_digits=12)),
                ('feeding_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Stores.feedingsession')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stores.inventoryitem')),
            ],
            options={
                'db_table': 'feeding_item',
            },
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stores.itemcategory'),
        ),
        migrations.CreateModel(
            name='OfficerIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('issue_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorised_issues', to='HumanResources.officer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stores.inventoryitem')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_items', to='HumanResources.officer')),
            ],
            options={
                'db_table': 'officer_issue',
            },
        ),
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIVE', 'Receive'), ('ISSUE', 'Issue'), ('RETURN', 'Return'), ('WRITE_OFF', 'Write Off'), ('LOSS', 'Loss'), ('DAMAGE', 'Damage')], max_length=15)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stores.inventoryitem')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HumanResources.officer')),
            ],
            options={
                'db_table': 'stock_ledger',
                'ordering': ['transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='StockReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=100, unique=True)),
                ('source', models.CharField(choices=[('PROVINCIAL_HQ', 'Provincial HQ'), ('NATIONAL_HQ', 'National HQ'), ('SUPPLIER', 'External Supplier'), ('TRANSFER', 'Inter-Station Transfer')], max_length=20)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HumanResources.officer')),
            ],
            options={
                'db_table': 'stock_receipt',
            },
        ),
        migrations.CreateModel(
            name='StockReceiptItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stores.inventoryitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Stores.stockreceipt')),
            ],
            options={
                'db_table': 'stock_receipt_item',
            },
        ),
        migrations.CreateModel(
            name='StockWriteOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('writeoff_date', models.DateField(default=django.utils.timezone.now)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approved_writeoffs', to='HumanResources.officer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stores.inventoryitem')),
            ],
            options={
                'db_table': 'stock_write_off',
            },
        ),
        migrations.CreateModel(
            name='StoreAuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('description', models.TextField()),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='HumanResources.officer')),
            ],
            options={
                'db_table': 'store_audit_trail',
            },
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('name', 'unit_of_measure')},
        ),
    ]
